### PR TITLE
FIX: Fixes #58 We always want $content (an array) passed to implode()

### LINKED ISSUE #58: Incorrect param from exec() passed to implode()
Look in `PDFTextExtractor::getRawOutput()`. the 3rd param `$err` passed to `exec()` will produce an integer value from `exec()`, being as it is the exit code from the shell invocation of `/usr/local/bin/pdftotext`.

The logic then goes on to pass it as the 2nd param to `implode()` which expects an array, not an int. I believe the original author meant to have passed `$content` instead.

```
exec(sprintf('%s %s - 2>&1', $this->bin('pdftotext'), escapeshellarg($path)), $content, $err);
if ($err) {
    ..

    throw new Exception(sprintf(
        'PDFTextExtractor->getContent() failed for %s: %s',
        $path,
        implode(PHP_EOL, $err) // <-- Here
    ));
}
```

### PR DESCRIPTION
**Pull request by phptek**

### CODE REVIEW

**Comment by phptek** [comment]
Rationale: I'm not sure what issue with Windows the replaced logic was trying to deal with, but in both logic forks an array being `$content` as returned by `exec()` should be passed to `implode()` in both regardless.

**Review by robbieaverill — COMMENTED** [review]
My assumption from the code would be that windows errors would be written to stderr, so this logic would capture that message. I think we need to double check these assumptions before merging this though.

**Comment by phptek** [comment]
Sure. Do what you need to do. All I can see is that $err (an int) was being passed to implode() that of course needs an array, regardless of whether or not that logic is triggered.

**Review by robbieaverill — APPROVED** [review]
I checked again, and this looks good to me. Thanks for the PR! I couldn't find anything online that would support the Windows compatibility comment here, and we are redirecting stderr to stdout, so 👍

**Pull request merged**
