### PR TITLE
MINOR: module support for Silverstripe 3.7

### PR DESCRIPTION
**Pull request by elliot-sawyer**

### CODE REVIEW

**Comment by elliot-sawyer** [comment]
@robbieaverill this may be a Travis problem? The tests pass locally on a fresh install of SS 3.7.2 running PHP 5.6. It's showing an error commonly seen on < PHP 7.1 (which passes, incidentally)

Here's the composer.json I'm using to test the project:
```
{
    "name": "silverstripe/installer",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.3.3",
        "silverstripe/cms": "3.7.2@stable",
        "silverstripe/framework": "3.7.2@stable",
        "silverstripe/reports": "3.7.2@stable",
        "silverstripe/siteconfig": "3.7.2@stable",
        "silverstripe-themes/simple": "3.1.*",
	"silverstripe/textextraction": "dev-upgrade/37"
    },
    "require-dev": {
        "phpunit/phpunit": "^3"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:elliot-sawyer/silverstripe-textextraction.git"
        }
    ],
    "extra": [],
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}

```

**Comment by robbieaverill** [comment]
I'll re-run them

**Comment by elliot-sawyer** [comment]
@robbieaverill I've rebased the branch against 2.1 but pushed before I could change the target branch on this request. Can you manually run Travis again?

**Comment by NightJar** [comment]
Restarted :)

**Comment by elliot-sawyer** [comment]
@NightJar These tests pass locally on PHP5.6. I'm not sure where the issue lies but I suspect an issue with the Travis configuration. Do you have any insights on the cause of the error?

**Comment by NightJar** [comment]
I guess you could check:
- [if this checkout contains the appropriate branch](https://travis-ci.org/silverstripe/silverstripe-textextraction/jobs/469809491#L452)
- that the arguments to [this function](https://travis-ci.org/silverstripe/silverstripe-textextraction/jobs/469809491#L649) are provided the correct way around, often I see `($value, $expected)` which is wrong, and should be `$expected, value)` in almost any PHPUnit assertion I can think of.

**Comment by robbieaverill** [comment]
You can also run through the Travis steps in a temp directory to recreate it in the same context, e.g. clone the repo, checkout your branch, run composer install then run the unit tests

**Comment by ScopeyNZ** [comment]
Re-triggering travis for this comment:

> I've rebased the branch against 2.1 but pushed before I could change the target branch on this request.

**Comment by robbieaverill** [comment]
This is a strange issue. I'll try and pick it up on my next bug day

**Comment by robbieaverill** [comment]
So far as I can tell, this is a legitimate bug. `FileTextExtractor::get_extractor_classes()` returns no results where it calls `$classes = ClassInfo::subclassesFor("FileTextExtractor");` - this happens in SS3.6 or lower with this patched code for textextraction.

@elliot-sawyer maybe we can just release this in a new minor release, and set the minimum SilverStripe version to 3.7.

**Comment by robbieaverill** [comment]
Interestingly the origin 2 branch just broke with the same issue, after I merged 2.1 into it. Will have a look.

**Pull request merged**
